### ISSUE TITLE
Memory leak, when Toggle is disabled

### ISSUE THREAD

**Issue by marcingum** [Ivan-1F/VillagerHelper#2]
When this mod is disabled (Settings => Villager Helper Configs => Toggle: Disabled), then memory continues to increase. 
Here is screen from VisualVM, with memory chart
![image](https://user-images.githubusercontent.com/16535726/116009018-7d34c100-a617-11eb-8147-2680c9b0a898.png)

Minecraft 1.16.5
fabric-loader-0.11.2-1.16.5
fabric-api-0.31.0+1.16.jar
Single player mode
About 40 villagers in loaded chunks

**Comment by Ivan-1F** [comment]
The current version is buggy, and I will try to fix it soon :(
